services:
  sampler_new:
    # image: barciewicz/sampler_new:latest
    build:
      context: ./sampler_new
      dockerfile: Dockerfile.dev
    ports:
      - 8002:8000
    tty: true

  # cv:
  #   build:
  #     context: ./cv
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - .:/app
  #   tty: true

  minsk:
    build:
      context: ./minsk
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    tty: true

  step_sequencer:
    image: barciewicz/step_sequencer:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
      - 8081:8081
    tty: true